security.jwt.token.secret-key: $2a$10$DFqi90hnWV4ddkUfovtOmetPxnYUFCEyYZV4wiE45xH5a7eUpoUbS

spring:
  data:
    mongodb:
      uri: mongodb+srv://mdDicta2023:YtTQsy7uWbkKyR7U@dicta.3pwgqtl.mongodb.net/bddictacolombia?retryWrites=true&w=majority
